name: Discord Webhook tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Discord Webhook action'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: Hello
          username: Testing
          tts: true
          allowed_mentions: "users, roles"
          allowed_user_mentions: "154148273307910144, 154148273307910144"
          allowed_role_mentions: "391539716966580225, 391539716966580225"

  mac-test:
    runs-on: macos-latest
    steps:
      - name: 'TEst Discord Webhook action'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: Hello from Mac
          username: Mac me baby

  win-test:
    runs-on: windows-latest
    steps:
      - name: 'Test Discord Webhook action'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: Hello from windows
          username: Windows Pro
          tts: "true"
