name: Discord Webhook tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Test the most basic usage'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: "Hello\nTest multiline content\n\\\"Testing\\\" hehe"
      - name: 'Test basic embed'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: "Hello\nTest multiline content"
          username: Testing
          tts: true
          allowed_mentions: ' '
          embed: '{
              "title": "Test",
              "description": "Testing....",
              "color": 65535
            }'

  mac-test:
    runs-on: macos-latest
    steps:
      - name: 'Test Discord Webhook action on mac'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: Hello from Mac
          username: Mac me baby

  win-test:
    runs-on: windows-latest
    steps:
      - name: 'Test Discord Webhook action on windows'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: "Hello from windows\nMultiline"
          username: Windows Pro
          tts: "true"
          embed: '[
              {
                "title": "First embed",
                "description": "One",
                "color": 65535
              },
              {
                "title": "Second embed",
                "description": "Two",
                "color": 16711680
              }
            ]'
