name: Discord Webhook tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test basic embed'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: "Hello\nTest multiline content"
          username: Linux
          embed: '{
              "title": "Test",
              "description": "Testing....

              Yeah, all to plan",
              "color": 65535
            }'

  mac-test:
    runs-on: macos-latest
    steps:
      - name: 'Test Discord Webhook action on mac'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: "Hello from Mac\nIndeed"
          username: Mac
          embed: '{
              "title": "Test on mac",
              "description": "Testing....

              You know what? This works",
              "color": 65535
            }'

  win-test:
    runs-on: windows-latest
    steps:
      - name: 'Test Discord Webhook action on windows'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: "Hello from windows\nMultiline"
          username: Windows
          tts: "true"
          embed: '[
              {
                "title": "First

                embed",
                "description": "One

                line",
                "color": 65535
              },
              {
                "title": "Second

                embed",
                "description": "Two

                line",
                "color": 16711680
              }
            ]'
