name: Discord Webhook tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Discord Webhook action'
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          content: Hello
          username: Testing
          tts: true
          embed: '[{
              "title": "Test",
              "description": "Testing...."
            }'

  # mac-test:
  #   runs-on: macos-latest
  #   steps:
  #     - name: 'Test Discord Webhook action'
  #       uses: MineBartekSA/discord-webhook@main
  #       with:
  #         webhook: ${{ secrets.WEBHOOK }}
  #         content: Hello from Mac
  #         username: Mac me baby

  # win-test:
  #   runs-on: windows-latest
  #   steps:
  #     - name: 'Test Discord Webhook action'
  #       uses: MineBartekSA/discord-webhook@main
  #       with:
  #         webhook: ${{ secrets.WEBHOOK }}
  #         content: Hello from windows
  #         username: Windows Pro
  #         tts: "true"
