name: Composite Discord Webhooks Action tests

on:
  workflow_dispatch

jobs:
  lin-test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        shell: bash
        run: wget https://http.cat/100
      - name: Test a complex message on Linux
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          username: Linux
          content: |
            Multiline text test.
            Working as expexted!
          embed: |
            title: Hello there!
            description: |
              In here, you can also
              make multiline strings
            fields:
              - name: Field one
                value: 1
              - name: Field two
                value: 2
            image:
              url: attachment://image.jpg
            footer:
              text: Footer text
          attachment: |
            file: 100
            filename: image.jpg

  mac-test:
    runs-on: macos-latest
    steps:
      - name: Prepare
        shell: bash
        run: wget https://http.cat/100
      - name: Test a complex message on Mac
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          username: Mac
          content: |
            Multiline text test.
            Working as expexted!
          embed: |
            title: Hello there!
            description: |
              In here, you can also
              make multiline strings
            fields:
              - name: Field one
                value: 1
              - name: Field two
                value: 2
            image:
              url: attachment://image.jpg
            footer:
              text: Footer text
          attachment: |
            file: 100
            filename: image.jpg

  win-test:
    runs-on: windows-latest
    steps:
      - name: Prepare
        shell: bash
        run: curl https://http.cat/100 > 100
      - name: Test a complex message on Windows
        uses: MineBartekSA/discord-webhook@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          username: Windows
          content: |
            Multiline text test.
            Working as expexted!
          embed: |
            title: Hello there!
            description: |
              In here, you can also
              make multiline strings
            fields:
              - name: Field one
                value: 1
              - name: Field two
                value: 2
            image:
              url: attachment://image.jpg
            footer:
              text: Footer text
          attachment: |
            file: 100
            filename: image.jpg
